{% set build = 0 %}
{% set version = "4.7" %}

# fstatat is only available on MacOS 10.10+
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.10"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.10"                # [osx and x86_64]
  
package:
  name: nnn
  version: {{ version }}

source:
  url: https://github.com/jarun/nnn/archive/v{{ version }}.tar.gz
  sha256: 81ccccc045bfd7ee3f1909cc443158ea0d1833f77d6342fd19c33864a2ab71d1

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - pkg-config
  host:
    - ncurses
    - readline
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
    - ncurses
    - readline

test:
  commands:
    - nnn -h

about:
  home: https://github.com/jarun/nnn/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Tiny, lightning fast, feature-packed file manager

extra:
  recipe-maintainers:
    - lebedov
