{% set version = "5.0" %}

package:
  name: nnn
  version: {{ version }}

source:
  url: https://github.com/jarun/nnn/archive/v{{ version }}.tar.gz
  sha256: 31e8fd85f3dd7ab2bf0525c3c0926269a1e6d35a5343a6714315642370d8605a
  patches:
    - nnn.patch

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - pkg-config
  host:
    - ncurses
    - readline

test:
  commands:
    - nnn -h

about:
  home: https://github.com/jarun/nnn/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Tiny, lightning fast, feature-packed file manager

extra:
  recipe-maintainers:
    - danielnachun
    - lebedov
