{% set build = 0 %}
{% set version = "3.7" %}

package:
  name: nnn
  version: {{ version }}

source:
  url: https://github.com/jarun/nnn/archive/v{{ version }}.tar.gz
  sha256: 7c330886e889ede19a6ceed274fed7d10cde58315e67f81fe3c2d7d7d49f657f

build:
  number: {{ build }}
  skip: true  # [win or osx]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - pkg-config
  host:
    - ncurses
    - readline
  run:
    - ncurses
    - readline

test:
  commands:
    - nnn -h

about:
  home: https://github.com/jarun/nnn/
  license: BSD
  license_file: LICENSE
  summary: Tiny, lightning fast, feature-packed file manager

extra:
  recipe-maintainers:
    - lebedov
