{% set version = "5.1" %}

package:
  name: nnn
  version: {{ version }}

source:
  url: https://github.com/jarun/nnn/archive/v{{ version }}.tar.gz
  sha256: 9faaff1e3f5a2fd3ed570a83f6fb3baf0bfc6ebd6a9abac16203d057ac3fffe3
  patches:
    - nnn.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - pkg-config
  host:
    - ncurses
    - readline

test:
  commands:
    - nnn -h

about:
  home: https://github.com/jarun/nnn/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Tiny, lightning fast, feature-packed file manager

extra:
  recipe-maintainers:
    - danielnachun
    - lebedov
