{% set build = 0 %}
{% set version = "2.5.1" %}

package:
    name: nnn
    version: {{version}}

source:
    url: https://github.com/jarun/nnn/archive/v{{version}}.tar.gz
    sha256: 47999a25af85669011b820a72e67316cc3280c7ee423323d1018d7b182f19463

build:
    number: {{build}}
    skip: true  # [win or osx]

requirements:
    build:
        - make
        - {{ compiler('c') }}
        - pkg-config
    host:
        - ncurses
        - readline <8.0a0
    run:
        - ncurses
        - readline <8.0a0

test:
    commands:
        - nnn -h

about:
    home: https://github.com/jarun/nnn/
    license: BSD
    summary: Tiny, lightning fast, feature-packed file manager

extra:
    recipe-maintainers:
        - lebedov
