{% set build = 0 %}
{% set version = "3.1" %}

package:
  name: nnn
  version: {{version}}

source:
  url: https://github.com/jarun/nnn/archive/v{{ version }}.tar.gz
  sha256: d70c21b4afa30fa733ab17bb8b45291e8651f2b823fad748ffbdb3b5c3fb0489

build:
  number: {{build}}
  skip: true  # [win or osx]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - pkg-config
  host:
    - ncurses
    - readline
  run:
    - ncurses
    - readline

test:
  commands:
    - nnn -h

about:
  home: https://github.com/jarun/nnn/
  license: BSD
  license_file: LICENSE
  summary: Tiny, lightning fast, feature-packed file manager

extra:
  recipe-maintainers:
    - lebedov
