{% set build = 0 %}
{% set version = "2.9" %}

package:
    name: nnn
    version: {{version}}

source:
    url: https://github.com/jarun/nnn/archive/v{{version}}.tar.gz
    sha256: a11e54469bb28173bba0dd1762b4648d4e79343927ba7f25067dfbf3db8e3b1d

build:
    number: {{build}}
    skip: true  # [win or osx]

requirements:
    build:
        - make
        - {{ compiler('c') }}
        - pkg-config
    host:
        - ncurses
        - readline
    run:
        - ncurses
        - readline

test:
    commands:
        - nnn -h

about:
    home: https://github.com/jarun/nnn/
    license: BSD
    license_file: LICENSE
    summary: Tiny, lightning fast, feature-packed file manager

extra:
    recipe-maintainers:
        - lebedov
