schema_version: 1

context:
  version: "5.2"

package:
  name: nnn
  version: ${{ version }}

source:
  url: https://github.com/jarun/nnn/archive/v${{ version }}.tar.gz
  sha256: f166eda5093ac8dcf8cbbc6224123a32c53cf37b82c5c1cb48e2e23352754030
  patches:
    - nnn.patch

build:
  number: 0
  skip: win

requirements:
  build:
    - make
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - pkg-config
  host:
    - ncurses
    - readline

tests:
  - script:
      - nnn -h

about:
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Tiny, lightning fast, feature-packed file manager
  homepage: https://github.com/jarun/nnn/

extra:
  recipe-maintainers:
    - danielnachun
    - lebedov
