schema_version: 1

context:
  version: "5.3"

package:
  name: nnn
  version: ${{ version }}

source:
  url: https://github.com/jarun/nnn/archive/v${{ version }}.tar.gz
  sha256: 79ee69f3ced7c0778d207df76b4d4d680636975ccda002eeb19d0917fcba3d36
  patches:
    - nnn.patch

build:
  number: 0
  skip: win

requirements:
  build:
    - make
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - pkg-config
  host:
    - ncurses
    - readline

tests:
  - script:
      - nnn -h

about:
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Tiny, lightning fast, feature-packed file manager
  homepage: https://github.com/jarun/nnn/

extra:
  recipe-maintainers:
    - danielnachun
    - lebedov
