travis:
  secure:
    BINSTAR_TOKEN: dXAtw5EQbItnLAkziWAApg67SoY8CjNa3poK0zLY64p97mW35YJWfOKZ6fy0x1YhJFMjZ02YR2TKoLK9nZvJnq/clW8U5Q9QrztXdhQoeUQQb6nUCVj+JItGTyipPcRxDLE6Nl7ecJZreYUq4WcJkBAJdehCfUmIzCK+Wy37WzDHAT4fh10itFsH6eH5rjWVkkqYop7s8M+1ik8G3Cp08BK97s/4wSaHzVk9j8mmT3WST1GWRu7GIv3FBePE9xPeoAuATbETU+3U1KoCuqrRSrjcVjJgQIu1VNBLML9azluc8iFnnCjJiRQneKeaXrT/73oMir7KjRRZbGZU12Yzzu7fMt4zmKN302ZHIi6cu7+8mqnSu2Sa0UlKalIGNTipYhbSzrL1UhL2DFxIji195gTohIRRKcTm6Pdyz+d2i6RJtblIljmqJjzqTMyjlBQ7ha9CpUI5CF2GmC1eMLRW4p4Uw3Nld7YvCNfXKKdfr6d583Yt8F/JifgCoo/GfX82BpNZqLYF2lRRsPDnXbuuU3OXuJnK6r+jKBOdyO5WO5zplu56APJvv7++mG/yBXQVI58Trwg6QhW5I0HBQCq9x2o7EAXDO75/Fd0WBSl2+CxPJbwbrQ7VJVH9yXfa+RDEo78vnx8hfHuPgJOZE/2bEvfPE0lmBAmqMmt+Xp3LLOc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
